services:
  - type: web
    name: ghosttalk-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app -w 1 --threads 2
    envVars:
      - key: BOT_TOKEN
        sync: false
